"""
Item and monster catalogs for the battle simulator.

Primary data: backend/app/data/wiki_catalog.json (636+ items, 100+ monsters)
generated by scripts/build_wiki_catalog.py from thebazaar.wiki.gg Cargo API.
Aligned with community databases such as Bazaar DB.

Hand-tuned overrides (optional): merge on top of wiki data for simulator fixes.
"""

from __future__ import annotations

import json
from pathlib import Path

from .engine import Item

_DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "wiki_catalog.json"


def _load_catalog() -> tuple[dict[str, dict], dict[str, dict]]:
    if not _DATA_PATH.is_file():
        raise FileNotFoundError(
            f"Missing {_DATA_PATH}. Run: python scripts/build_wiki_catalog.py"
        )
    raw = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
    items = dict(raw["items"])
    monsters = dict(raw["monsters"])
    for item_id, patch in ITEM_PATCHES.items():
        if item_id in items:
            merged = {**items[item_id], **patch}
            items[item_id] = merged
        else:
            items[item_id] = patch
    for mid, patch in MONSTER_PATCHES.items():
        if mid in monsters:
            monsters[mid] = {**monsters[mid], **patch}
        else:
            monsters[mid] = patch
    return items, monsters


# Optional: per-id overrides after wiki import (tuning / bugfixes)
ITEM_PATCHES: dict[str, dict] = {}

MONSTER_PATCHES: dict[str, dict] = {}

ITEMS_CATALOG, MONSTERS = _load_catalog()


def build_item(item_id: str, idx: int = 0) -> Item:
    """Create an Item instance from catalog entry."""
    data = ITEMS_CATALOG[item_id]
    return Item(
        id=f"{item_id}_{idx}",
        name=data["name"],
        board_pos=idx,
        cooldown_ms=data["cooldown_ms"],
        damage=data.get("damage", 0.0),
        healing=data.get("healing", 0.0),
        shield_amount=data.get("shield_amount", 0.0),
        crit_chance=data.get("crit_chance", 0.0),
        crit_multiplier=data.get("crit_multiplier", 2.0),
        multicast=data.get("multicast", 1),
        applies_burn=data.get("applies_burn", 0.0),
        applies_freeze=data.get("applies_freeze", 0),
        applies_poison=data.get("applies_poison", 0.0),
        applies_haste=data.get("applies_haste", 0),
        applies_slow=data.get("applies_slow", 0),
        applies_charge=data.get("applies_charge", 0),
    )


def get_catalog_items() -> list[dict]:
    """Return catalog as list of dicts for API."""
    result = []
    for item_id, data in ITEMS_CATALOG.items():
        entry = {"id": item_id, "tier": data.get("tier", "bronze")}
        entry.update(data)
        result.append(entry)
    return result
