"""
The Bazaar items catalog — adapted to the new engine API.
Item fields: damage, healing, shield_amount, crit_chance, crit_multiplier,
             multicast, applies_burn, applies_freeze, applies_poison,
             applies_haste, applies_slow, applies_charge
"""

from .engine import Item, Side, PlayerState, BattleState, BattleSimulator

ITEMS_CATALOG: dict[str, dict] = {
    # === WEAPONS ===
    "sword": {
        "name": "Sword",
        "desc": "Deal 40 damage. 25% crit chance.",
        "category": "weapon",
        "tier": "bronze",
        "size": "small",
        "cooldown_ms": 3000,
        "multicast": 1,
        "damage": 40.0,
        "crit_chance": 0.25,
    },
    "heavy_axe": {
        "name": "Heavy Axe",
        "desc": "Deal 70 damage. Slow but devastating.",
        "category": "weapon",
        "tier": "silver",
        "size": "medium",
        "cooldown_ms": 5000,
        "multicast": 1,
        "damage": 70.0,
        "crit_chance": 0.15,
    },
    "twin_daggers": {
        "name": "Twin Daggers",
        "desc": "Deal 20 damage x2. 30% crit chance.",
        "category": "weapon",
        "tier": "silver",
        "size": "small",
        "cooldown_ms": 2500,
        "multicast": 2,
        "damage": 20.0,
        "crit_chance": 0.30,
    },
    "storm_glaive": {
        "name": "Storm Glaive",
        "desc": "Deal 25 damage x3. Fast multicast.",
        "category": "weapon",
        "tier": "gold",
        "size": "medium",
        "cooldown_ms": 4000,
        "multicast": 3,
        "damage": 25.0,
        "crit_chance": 0.10,
    },
    "shadow_katana": {
        "name": "Shadow Katana",
        "desc": "Deal 22 damage x4. 20% crit chance.",
        "category": "weapon",
        "tier": "diamond",
        "size": "medium",
        "cooldown_ms": 3500,
        "multicast": 4,
        "damage": 22.0,
        "crit_chance": 0.20,
    },
    "divine_avenger": {
        "name": "Divine Avenger",
        "desc": "Deal 35 damage x3, heal 15. Legendary combo.",
        "category": "weapon",
        "tier": "legendary",
        "size": "large",
        "cooldown_ms": 5000,
        "multicast": 3,
        "damage": 35.0,
        "healing": 15.0,
        "crit_chance": 0.15,
    },

    # === BURN ===
    "torch": {
        "name": "Torch",
        "desc": "Deal 20 damage, apply 15 Burn.",
        "category": "weapon",
        "tier": "bronze",
        "size": "small",
        "cooldown_ms": 4000,
        "multicast": 1,
        "damage": 20.0,
        "applies_burn": 15.0,
    },
    "flame_blade": {
        "name": "Flame Blade",
        "desc": "Deal 30 damage, apply 25 Burn.",
        "category": "weapon",
        "tier": "silver",
        "size": "medium",
        "cooldown_ms": 5000,
        "multicast": 1,
        "damage": 30.0,
        "applies_burn": 25.0,
    },
    "inferno_staff": {
        "name": "Inferno Staff",
        "desc": "Deal 15 damage x2, apply 20 Burn each.",
        "category": "weapon",
        "tier": "gold",
        "size": "large",
        "cooldown_ms": 6000,
        "multicast": 2,
        "damage": 15.0,
        "applies_burn": 20.0,
    },

    # === POISON ===
    "vial": {
        "name": "Poison Vial",
        "desc": "Apply 8 Poison per second.",
        "category": "potion",
        "tier": "bronze",
        "size": "small",
        "cooldown_ms": 6000,
        "multicast": 1,
        "applies_poison": 8.0,
    },
    "poison_dagger": {
        "name": "Poison Dagger",
        "desc": "Deal 10 damage x2, apply 6 Poison.",
        "category": "weapon",
        "tier": "silver",
        "size": "small",
        "cooldown_ms": 4000,
        "multicast": 2,
        "damage": 10.0,
        "applies_poison": 6.0,
    },
    "plague_totem": {
        "name": "Plague Totem",
        "desc": "Apply 20 Poison and 1.5s Slow.",
        "category": "property",
        "tier": "gold",
        "size": "medium",
        "cooldown_ms": 8000,
        "multicast": 1,
        "applies_poison": 20.0,
        "applies_slow": 1500,
    },

    # === FREEZE ===
    "ice_staff": {
        "name": "Ice Staff",
        "desc": "Deal 15 damage, Freeze enemy for 2s.",
        "category": "weapon",
        "tier": "silver",
        "size": "medium",
        "cooldown_ms": 7000,
        "multicast": 1,
        "damage": 15.0,
        "applies_freeze": 2000,
    },
    "frost_ward": {
        "name": "Frost Ward",
        "desc": "Shield 35, Freeze enemy for 2.5s.",
        "category": "property",
        "tier": "silver",
        "size": "medium",
        "cooldown_ms": 9000,
        "multicast": 1,
        "shield_amount": 35.0,
        "applies_freeze": 2500,
    },
    "blizzard_orb": {
        "name": "Blizzard Orb",
        "desc": "Deal 10 damage x2, Freeze 1.5s each.",
        "category": "weapon",
        "tier": "gold",
        "size": "medium",
        "cooldown_ms": 10000,
        "multicast": 2,
        "applies_freeze": 1500,
        "damage": 10.0,
    },

    # === SHIELDS / DEFENSE ===
    "buckler": {
        "name": "Buckler",
        "desc": "Gain 30 Shield.",
        "category": "apparel",
        "tier": "bronze",
        "size": "small",
        "cooldown_ms": 5000,
        "multicast": 1,
        "shield_amount": 30.0,
    },
    "aegis_barrier": {
        "name": "Aegis Barrier",
        "desc": "Gain 80 Shield.",
        "category": "apparel",
        "tier": "gold",
        "size": "medium",
        "cooldown_ms": 7000,
        "multicast": 1,
        "shield_amount": 80.0,
    },
    "titan_shield": {
        "name": "Titan Shield",
        "desc": "Gain 120 Shield. Massive defense.",
        "category": "apparel",
        "tier": "diamond",
        "size": "large",
        "cooldown_ms": 8000,
        "multicast": 1,
        "shield_amount": 120.0,
    },

    # === HEALING ===
    "health_potion": {
        "name": "Health Potion",
        "desc": "Heal 40 HP.",
        "category": "potion",
        "tier": "bronze",
        "size": "small",
        "cooldown_ms": 6000,
        "multicast": 1,
        "healing": 40.0,
    },
    "regeneration_orb": {
        "name": "Regeneration Orb",
        "desc": "Heal 25 HP. Fast cooldown.",
        "category": "potion",
        "tier": "silver",
        "size": "small",
        "cooldown_ms": 4000,
        "multicast": 1,
        "healing": 25.0,
    },
    "holy_grail": {
        "name": "Holy Grail",
        "desc": "Heal 30 HP x2 and Shield 20.",
        "category": "potion",
        "tier": "legendary",
        "size": "medium",
        "cooldown_ms": 5000,
        "multicast": 2,
        "healing": 30.0,
        "shield_amount": 20.0,
    },

    # === HASTE / SLOW / UTILITY ===
    "haste_boots": {
        "name": "Haste Boots",
        "desc": "Apply Haste for 2s to all your items.",
        "category": "apparel",
        "tier": "bronze",
        "size": "small",
        "cooldown_ms": 6000,
        "multicast": 1,
        "applies_haste": 2000,
    },
    "chrono_crystal": {
        "name": "Chrono Crystal",
        "desc": "Haste 3s for you, Slow 2s for enemy.",
        "category": "tool",
        "tier": "silver",
        "size": "small",
        "cooldown_ms": 7000,
        "multicast": 1,
        "applies_haste": 3000,
        "applies_slow": 2000,
    },
    "hex_totem": {
        "name": "Hex Totem",
        "desc": "Deal 15 damage, Slow 3s, Poison 5.",
        "category": "property",
        "tier": "gold",
        "size": "medium",
        "cooldown_ms": 8000,
        "multicast": 1,
        "damage": 15.0,
        "applies_slow": 3000,
        "applies_poison": 5.0,
    },

    # === COMBO ===
    "vampiric_fang": {
        "name": "Vampiric Fang",
        "desc": "Deal 25 damage x2, heal 15 per hit.",
        "category": "weapon",
        "tier": "gold",
        "size": "small",
        "cooldown_ms": 5000,
        "multicast": 2,
        "damage": 25.0,
        "healing": 15.0,
    },
    "apocalypse_blade": {
        "name": "Apocalypse Blade",
        "desc": "Deal 18 damage x5, Burn 5 each. 10% crit.",
        "category": "weapon",
        "tier": "legendary",
        "size": "large",
        "cooldown_ms": 4000,
        "multicast": 5,
        "damage": 18.0,
        "applies_burn": 5.0,
        "crit_chance": 0.10,
    },
}


MONSTERS: dict[str, dict] = {
    "banannibal": {
        "name": "Banannibal",
        "hp": 100,
        "day": 1,
        "tier": "bronze",
        "image": "https://thebazaar.wiki.gg/images/Monster_Banannibal_Portrait.png",
        "items": ["sword", "buckler"],
    },
    "fanged_inglet": {
        "name": "Fanged Inglet",
        "hp": 100,
        "day": 1,
        "tier": "bronze",
        "image": "https://thebazaar.wiki.gg/images/Monster_Fanged_Inglet_Portrait.png",
        "items": ["sword", "vial"],
    },
    "pyro": {
        "name": "Pyro",
        "hp": 150,
        "day": 1,
        "tier": "bronze",
        "image": "https://thebazaar.wiki.gg/images/Monster_Pyro_Portrait.png",
        "items": ["torch", "buckler"],
    },
    "coconut_crab": {
        "name": "Coconut Crab",
        "hp": 200,
        "day": 2,
        "tier": "bronze",
        "image": "https://thebazaar.wiki.gg/images/Monster_Coconut_Crab_Portrait.png",
        "items": ["buckler", "health_potion", "sword"],
    },
    "giant_mosquito": {
        "name": "Giant Mosquito",
        "hp": 200,
        "day": 2,
        "tier": "bronze",
        "image": "https://thebazaar.wiki.gg/images/Monster_Giant_Mosquito_Portrait.png",
        "items": ["poison_dagger", "haste_boots"],
    },
    "shadow_assassin": {
        "name": "Shadow Assassin",
        "hp": 350,
        "day": 4,
        "tier": "silver",
        "image": "https://thebazaar.wiki.gg/images/Monster_Shadow_Assassin_Portrait.png",
        "items": ["shadow_katana", "poison_dagger", "twin_daggers"],
    },
    "frost_elemental": {
        "name": "Frost Elemental",
        "hp": 400,
        "day": 5,
        "tier": "silver",
        "image": "https://thebazaar.wiki.gg/images/Monster_Frost_Colossus_Portrait.png",
        "items": ["ice_staff", "frost_ward", "regeneration_orb"],
    },
    "zookeeper": {
        "name": "Zookeeper",
        "hp": 500,
        "day": 6,
        "tier": "gold",
        "image": "https://thebazaar.wiki.gg/images/Monster_Zookeeper_Portrait.png",
        "items": ["heavy_axe", "vampiric_fang", "aegis_barrier", "haste_boots"],
    },
    "oasis_guardian": {
        "name": "Oasis Guardian",
        "hp": 600,
        "day": 7,
        "tier": "gold",
        "image": "https://thebazaar.wiki.gg/images/Monster_Oasis_Guardian_Portrait.png",
        "items": ["titan_shield", "aegis_barrier", "storm_glaive", "health_potion"],
    },
    "dragon": {
        "name": "Dragon",
        "hp": 3675,
        "day": 8,
        "tier": "legendary",
        "image": "https://thebazaar.wiki.gg/images/Monster_Dragon_Portrait.png",
        "items": ["apocalypse_blade", "divine_avenger", "frost_ward", "titan_shield", "inferno_staff"],
    },
}


def build_item(item_id: str, idx: int = 0) -> Item:
    """Create an Item instance from catalog entry."""
    data = ITEMS_CATALOG[item_id]
    return Item(
        id=f"{item_id}_{idx}",
        name=data["name"],
        board_pos=idx,
        cooldown_ms=data["cooldown_ms"],
        damage=data.get("damage", 0.0),
        healing=data.get("healing", 0.0),
        shield_amount=data.get("shield_amount", 0.0),
        crit_chance=data.get("crit_chance", 0.0),
        crit_multiplier=data.get("crit_multiplier", 2.0),
        multicast=data.get("multicast", 1),
        applies_burn=data.get("applies_burn", 0.0),
        applies_freeze=data.get("applies_freeze", 0),
        applies_poison=data.get("applies_poison", 0.0),
        applies_haste=data.get("applies_haste", 0),
        applies_slow=data.get("applies_slow", 0),
        applies_charge=data.get("applies_charge", 0),
    )


def get_catalog_items() -> list[dict]:
    """Return catalog as list of dicts for API."""
    result = []
    for item_id, data in ITEMS_CATALOG.items():
        entry = {"id": item_id, "tier": data.get("tier", "bronze")}
        entry.update(data)
        result.append(entry)
    return result
